In [38]:
from PIL import Image
from numpy import asarray
pixel_data = []
ids = []
for i in range(1,6387):
    try:
        image = Image.open("GarageImages/image" + str(i) + ".jpg").convert('LA').resize((64,64), Image.ANTIALIAS)
        data = asarray(image)
        image.save("GarageImages/grayscale" +  str(i) + ".png")
        pixel_data.append(data[:,:,0].flatten())
        ids.append(i)
    except FileNotFoundError:
        print("No image for " + str(i))

No image for 21
No image for 22
No image for 23
No image for 24
No image for 25
No image for 26
No image for 27
No image for 28
No image for 29
No image for 30
No image for 31
No image for 32
No image for 33
No image for 34
No image for 35
No image for 36
No image for 37
No image for 38
No image for 39
No image for 40
No image for 41
No image for 42
No image for 43
No image for 44
No image for 45
No image for 46
No image for 47
No image for 48
No image for 49
No image for 50
No image for 51
No image for 52
No image for 53
No image for 54
No image for 55
No image for 56
No image for 57
No image for 58
No image for 59
No image for 60
No image for 61
No image for 62
No image for 63
No image for 64
No image for 65
No image for 66
No image for 67
No image for 68
No image for 69
No image for 70
No image for 121
No image for 122
No image for 123
No image for 124
No image for 125
No image for 126
No image for 127
No image for 128
No image for 129
No image for 130
No image for 131
No image for 

No image for 1019
No image for 1020
No image for 1021
No image for 1022
No image for 1023
No image for 1024
No image for 1025
No image for 1026
No image for 1027
No image for 1028
No image for 1029
No image for 1030
No image for 1031
No image for 1032
No image for 1033
No image for 1034
No image for 1035
No image for 1036
No image for 1037
No image for 1038
No image for 1039
No image for 1040
No image for 1041
No image for 1042
No image for 1043
No image for 1044
No image for 1045
No image for 1046
No image for 1047
No image for 1048
No image for 1049
No image for 1050
No image for 1051
No image for 1052
No image for 1053
No image for 1054
No image for 1055
No image for 1056
No image for 1057
No image for 1058
No image for 1059
No image for 1060
No image for 1061
No image for 1062
No image for 1063
No image for 1064
No image for 1065
No image for 1066
No image for 1067
No image for 1068
No image for 1069
No image for 1070
No image for 1071
No image for 1072
No image for 1120
No image f

No image for 1919
No image for 1920
No image for 1921
No image for 1922
No image for 1923
No image for 1924
No image for 1925
No image for 1926
No image for 1927
No image for 1928
No image for 1929
No image for 1930
No image for 1931
No image for 1932
No image for 1933
No image for 1934
No image for 1935
No image for 1936
No image for 1937
No image for 1938
No image for 1939
No image for 1940
No image for 1941
No image for 1942
No image for 1943
No image for 1944
No image for 1945
No image for 1946
No image for 1947
No image for 1948
No image for 1949
No image for 1950
No image for 1951
No image for 1952
No image for 1953
No image for 1954
No image for 1955
No image for 1956
No image for 1957
No image for 1958
No image for 1959
No image for 1960
No image for 1961
No image for 1962
No image for 1963
No image for 1964
No image for 1965
No image for 1966
No image for 1967
No image for 1968
No image for 1969
No image for 1970
No image for 1971
No image for 1972
No image for 1973
No image f

No image for 2919
No image for 2920
No image for 2921
No image for 2922
No image for 2923
No image for 2924
No image for 2925
No image for 2926
No image for 2927
No image for 2928
No image for 2929
No image for 2930
No image for 2931
No image for 2932
No image for 2933
No image for 2934
No image for 2935
No image for 2936
No image for 2937
No image for 2938
No image for 2939
No image for 2940
No image for 2941
No image for 2942
No image for 2943
No image for 2944
No image for 2945
No image for 2946
No image for 2947
No image for 2948
No image for 2949
No image for 2950
No image for 2951
No image for 2952
No image for 2953
No image for 2954
No image for 2955
No image for 2956
No image for 2957
No image for 2958
No image for 2959
No image for 2960
No image for 2961
No image for 2962
No image for 2963
No image for 2964
No image for 2965
No image for 2966
No image for 2967
No image for 2968
No image for 2969
No image for 2970
No image for 2971
No image for 2972
No image for 2973
No image f

No image for 3816
No image for 3817
No image for 3818
No image for 3819
No image for 3820
No image for 3821
No image for 3822
No image for 3823
No image for 3824
No image for 3825
No image for 3826
No image for 3827
No image for 3828
No image for 3829
No image for 3830
No image for 3831
No image for 3832
No image for 3833
No image for 3834
No image for 3835
No image for 3836
No image for 3837
No image for 3838
No image for 3839
No image for 3840
No image for 3841
No image for 3842
No image for 3843
No image for 3844
No image for 3845
No image for 3846
No image for 3847
No image for 3848
No image for 3849
No image for 3850
No image for 3851
No image for 3852
No image for 3853
No image for 3854
No image for 3855
No image for 3856
No image for 3857
No image for 3858
No image for 3859
No image for 3860
No image for 3861
No image for 3862
No image for 3863
No image for 3864
No image for 3865
No image for 3866
No image for 3867
No image for 3916
No image for 3917
No image for 3918
No image f

No image for 5011
No image for 5012
No image for 5013
No image for 5014
No image for 5015
No image for 5016
No image for 5017
No image for 5018
No image for 5019
No image for 5020
No image for 5021
No image for 5022
No image for 5023
No image for 5024
No image for 5025
No image for 5026
No image for 5027
No image for 5028
No image for 5029
No image for 5030
No image for 5031
No image for 5032
No image for 5033
No image for 5034
No image for 5035
No image for 5036
No image for 5037
No image for 5038
No image for 5039
No image for 5040
No image for 5041
No image for 5042
No image for 5043
No image for 5044
No image for 5045
No image for 5046
No image for 5047
No image for 5048
No image for 5049
No image for 5050
No image for 5051
No image for 5052
No image for 5053
No image for 5054
No image for 5055
No image for 5056
No image for 5057
No image for 5058
No image for 5059
No image for 5060
No image for 5061
No image for 5062
No image for 5063
No image for 5064
No image for 5065
No image f

No image for 6051
No image for 6052
No image for 6053
No image for 6054
No image for 6055
No image for 6056
No image for 6057
No image for 6058
No image for 6109
No image for 6110
No image for 6111
No image for 6112
No image for 6113
No image for 6114
No image for 6115
No image for 6116
No image for 6117
No image for 6118
No image for 6119
No image for 6120
No image for 6121
No image for 6122
No image for 6123
No image for 6124
No image for 6125
No image for 6126
No image for 6127
No image for 6128
No image for 6129
No image for 6130
No image for 6131
No image for 6132
No image for 6133
No image for 6134
No image for 6135
No image for 6136
No image for 6137
No image for 6138
No image for 6139
No image for 6140
No image for 6141
No image for 6142
No image for 6143
No image for 6144
No image for 6145
No image for 6146
No image for 6147
No image for 6148
No image for 6149
No image for 6150
No image for 6151
No image for 6152
No image for 6153
No image for 6154
No image for 6155
No image f

In [61]:
pixel_data

[array([116, 125, 186, ...,  71,  66,  58], dtype=uint8),
 array([151, 157, 163, ..., 101, 102,  97], dtype=uint8),
 array([254, 254, 254, ..., 153, 152, 154], dtype=uint8),
 array([199, 201, 201, ..., 132, 126, 121], dtype=uint8),
 array([123, 115, 122, ..., 137, 136, 134], dtype=uint8),
 array([177, 177, 177, ..., 182, 186, 192], dtype=uint8),
 array([ 90, 120, 158, ..., 132, 146, 139], dtype=uint8),
 array([112, 112, 113, ..., 219, 208, 212], dtype=uint8),
 array([136, 136, 136, ..., 108, 100, 104], dtype=uint8),
 array([210, 215, 211, ..., 108, 106, 103], dtype=uint8),
 array([16, 29, 38, ..., 82, 70, 56], dtype=uint8),
 array([180, 185, 192, ..., 216, 211, 211], dtype=uint8),
 array([184,  82,  68, ..., 202, 199, 196], dtype=uint8),
 array([ 87, 108, 180, ..., 110, 109, 107], dtype=uint8),
 array([ 86,  67,  61, ..., 124, 111,  79], dtype=uint8),
 array([218, 220, 221, ..., 175, 174, 177], dtype=uint8),
 array([10, 29, 44, ..., 20, 30, 23], dtype=uint8),
 array([ 24,  23,  24, ...

In [72]:
import pandas as pd
df = pd.DataFrame(columns = ['ID'])
df['ID'] = ids
for j in range(0, 4096):
    transformed = []
    for i in pixel_data:
        transformed.append(i[j])
    column_name = "pixel"
    column_name += str(j)
    df[column_name] = transformed
df.head()

ID  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0   1     116     125     186     205     193     201     178     200     215   
1   2     151     157     163     167     172     178     179     182     184   
2   3     254     254     254     254     254     254     254     254     254   
3   4     199     201     201     202     204     204     204     206     208   
4   5     123     115     122     122     123     123     124     127     131   

   ...  pixel4086  pixel4087  pixel4088  pixel4089  pixel4090  pixel4091  \
0  ...         91         86         82         80         78         74   
1  ...        102         98         95         98         96        100   
2  ...        146        142        147        148        153        148   
3  ...        133        136        140        140        142        144   
4  ...        137        137        139        138        137        137   

   pixel4092  pixel4093  pixel4094  pixel4095  
0         71         71         66         58  
1        101        101        102         97  
2        150        153        152        154  
3        141        132        126        121  
4        137        137        136        134  

[5 rows x 4097 columns]

In [69]:
labels_df = pd.read_csv('garage_door_labels.csv')
labels_df.head()

ID  GarageDoorEntranceIndicator  AllGarageDoorEntrancesVisible
0  4286                            0                              0
1  5786                            1                              1
2  3499                            1                              1
3  5591                            1                              1
4     2                            1                              0

In [75]:
training_set = pd.merge(labels_df, df, how="inner", on="ID")
training_set = training_set.sort_values("ID")
training_set.head()

ID  GarageDoorEntranceIndicator  AllGarageDoorEntrancesVisible  pixel0  \
4     2                            1                              0     151   
5     8                            1                              0     112   
48   13                            1                              1     184   
66   15                            1                              1      86   
100  16                            0                              0     218   

     pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  ...  pixel4086  \
4       157     163     167     172     178     179  ...        102   
5       112     113     113     113     114     114  ...        229   
48       82      68      72      70      69      72  ...        210   
66       67      61      69      63      65      52  ...        179   
100     220     221     224     226     228     229  ...        185   

     pixel4087  pixel4088  pixel4089  pixel4090  pixel4091  pixel4092  \
4           98         95         98         96        100        101   
5          241        249        250        243        236        232   
48         209        208        206        206        203        201   
66         179        177        175        175        170        169   
100        184        182        180        180        173        175   

     pixel4093  pixel4094  pixel4095  
4          101        102         97  
5          219        208        212  
48         202        199        196  
66         124        111         79  
100        175        174        177  

[5 rows x 4099 columns]

In [80]:
X = training_set.loc[:,'pixel0':'pixel4095']
Y = training_set['GarageDoorEntranceIndicator']

In [95]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(1000, 100, 100, 4), max_iter = 1000)
mlp.fit(X, Y)
mlp.score(X, Y)

0.6916666666666667

In [96]:
from sklearn.model_selection import cross_val_score
cross_val_score(mlp, X, Y, cv=5)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([0.68      , 0.32      , 0.70833333, 0.69565217, 0.69565217])