In [78]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
warnings.filterwarnings('ignore')

In [79]:
postgres_user = 'dsbc_student'
postgres_pw = '7*.8G9QH21'
postgres_host = '142.93.121.174'
postgres_port = '5432'
postgres_db = 'useducation'

engine = create_engine('postgresql://{}:{}@{}:{}/{}'.format(
    postgres_user, postgres_pw, postgres_host, postgres_port, postgres_db))

edu_df = pd.read_sql_query('select * from useducation',con=engine)
edu_df

PRIMARY_KEY                 STATE  YEAR  ENROLL  \
0                  1992_ALABAMA               ALABAMA  1992     NaN   
1                   1992_ALASKA                ALASKA  1992     NaN   
2                  1992_ARIZONA               ARIZONA  1992     NaN   
3                 1992_ARKANSAS              ARKANSAS  1992     NaN   
4               1992_CALIFORNIA            CALIFORNIA  1992     NaN   
5                 1992_COLORADO              COLORADO  1992     NaN   
6              1992_CONNECTICUT           CONNECTICUT  1992     NaN   
7                 1992_DELAWARE              DELAWARE  1992     NaN   
8     1992_DISTRICT_OF_COLUMBIA  DISTRICT_OF_COLUMBIA  1992     NaN   
9                  1992_FLORIDA               FLORIDA  1992     NaN   
10                 1992_GEORGIA               GEORGIA  1992     NaN   
11                  1992_HAWAII                HAWAII  1992     NaN   
12                   1992_IDAHO                 IDAHO  1992     NaN   
13                1992_ILLINOIS              ILLINOIS  1992     NaN   
14                 1992_INDIANA               INDIANA  1992     NaN   
15                    1992_IOWA                  IOWA  1992     NaN   
16                  1992_KANSAS                KANSAS  1992     NaN   
17                1992_KENTUCKY              KENTUCKY  1992     NaN   
18               1992_LOUISIANA             LOUISIANA  1992     NaN   
19                   1992_MAINE                 MAINE  1992     NaN   
20                1992_MARYLAND              MARYLAND  1992     NaN   
21           1992_MASSACHUSETTS         MASSACHUSETTS  1992     NaN   
22                1992_MICHIGAN              MICHIGAN  1992     NaN   
23               1992_MINNESOTA             MINNESOTA  1992     NaN   
24             1992_MISSISSIPPI           MISSISSIPPI  1992     NaN   
25                1992_MISSOURI              MISSOURI  1992     NaN   
26                 1992_MONTANA               MONTANA  1992     NaN   
27                1992_NEBRASKA              NEBRASKA  1992     NaN   
28                  1992_NEVADA                NEVADA  1992     NaN   
29           1992_NEW_HAMPSHIRE         NEW_HAMPSHIRE  1992     NaN   
...                         ...                   ...   ...     ...   
1462                  2017_IOWA                  IOWA  2017     NaN   
1463                2017_KANSAS                KANSAS  2017     NaN   
1464              2017_KENTUCKY              KENTUCKY  2017     NaN   
1465             2017_LOUISIANA             LOUISIANA  2017     NaN   
1466                 2017_MAINE                 MAINE  2017     NaN   
1467              2017_MARYLAND              MARYLAND  2017     NaN   
1468         2017_MASSACHUSETTS         MASSACHUSETTS  2017     NaN   
1469              2017_MICHIGAN              MICHIGAN  2017     NaN   
1470             2017_MINNESOTA             MINNESOTA  2017     NaN   
1471           2017_MISSISSIPPI           MISSISSIPPI  2017     NaN   
1472              2017_MISSOURI              MISSOURI  2017     NaN   
1473               2017_MONTANA               MONTANA  2017     NaN   
1474              2017_NEBRASKA              NEBRASKA  2017     NaN   
1475                2017_NEVADA                NEVADA  2017     NaN   
1476         2017_NEW_HAMPSHIRE         NEW_HAMPSHIRE  2017     NaN   
1477            2017_NEW_JERSEY            NEW_JERSEY  2017     NaN   
1478            2017_NEW_MEXICO            NEW_MEXICO  2017     NaN   
1479              2017_NEW_YORK              NEW_YORK  2017     NaN   
1480        2017_NORTH_CAROLINA        NORTH_CAROLINA  2017     NaN   
1481          2017_NORTH_DAKOTA          NORTH_DAKOTA  2017     NaN   
1482                  2017_OHIO                  OHIO  2017     NaN   
1483             2017_TENNESSEE             TENNESSEE  2017     NaN   
1484                 2017_TEXAS                 TEXAS  2017     NaN   
1485                  2017_UTAH                  UTAH  2017     NaN   
1486               2017_VERMONT             

In [80]:
edu_df.sort_values(by = ['STATE', 'YEAR'], inplace = True)
edu_df

PRIMARY_KEY      STATE  YEAR    ENROLL  TOTAL_REVENUE  \
0       1992_ALABAMA    ALABAMA  1992       NaN      2678885.0   
52      1993_ALABAMA    ALABAMA  1993  727716.0      2827391.0   
104     1994_ALABAMA    ALABAMA  1994  730004.0      2970223.0   
157     1995_ALABAMA    ALABAMA  1995  727480.0      3367437.0   
209     1996_ALABAMA    ALABAMA  1996  735912.0      3365113.0   
260     1997_ALABAMA    ALABAMA  1997  737386.0      3981788.0   
312     1998_ALABAMA    ALABAMA  1998  739321.0      4140537.0   
363     1999_ALABAMA    ALABAMA  1999  737639.0      4471546.0   
416     2000_ALABAMA    ALABAMA  2000  730184.0      4885917.0   
468     2001_ALABAMA    ALABAMA  2001  728532.0      4832946.0   
520     2002_ALABAMA    ALABAMA  2002  726367.0      5128559.0   
572     2003_ALABAMA    ALABAMA  2003  727900.0      5196054.0   
624     2004_ALABAMA    ALABAMA  2004  730418.0      5356113.0   
676     2005_ALABAMA    ALABAMA  2005  729342.0      5889966.0   
727     2006_ALABAMA    ALABAMA  2006  743265.0      6364028.0   
780     2007_ALABAMA    ALABAMA  2007  743273.0      7069040.0   
832     2008_ALABAMA    ALABAMA  2008  742919.0      7726213.0   
887     2009_ALABAMA    ALABAMA  2009  745668.0      7186390.0   
940     2010_ALABAMA    ALABAMA  2010  748889.0      7281058.0   
993     2011_ALABAMA    ALABAMA  2011  746933.0      7376725.0   
1044    2012_ALABAMA    ALABAMA  2012  744621.0      7136949.0   
1096    2013_ALABAMA    ALABAMA  2013  744548.0      7197439.0   
1148    2014_ALABAMA    ALABAMA  2014  740081.0      7357267.0   
1199    2015_ALABAMA    ALABAMA  2015  734974.0      7360222.0   
1250    2016_ALABAMA    ALABAMA  2016  734652.0      7498567.0   
1447    2017_ALABAMA    ALABAMA  2017       NaN            NaN   
1        1992_ALASKA     ALASKA  1992       NaN      1049591.0   
53       1993_ALASKA     ALASKA  1993  121156.0      1191398.0   
105      1994_ALASKA     ALASKA  1994  123868.0      1052282.0   
158      1995_ALASKA     ALASKA  1995  125421.0      1117068.0   
...              ...        ...   ...       ...            ...   
1197  2014_WISCONSIN  WISCONSIN  2014  865119.0     11330253.0   
1248  2015_WISCONSIN  WISCONSIN  2015  861813.0     11637376.0   
808   2016_WISCONSIN  WISCONSIN  2016  857736.0     11697466.0   
1490  2017_WISCONSIN  WISCONSIN  2017       NaN            NaN   
51      1992_WYOMING    WYOMING  1992       NaN       629748.0   
103     1993_WYOMING    WYOMING  1993  100313.0       615130.0   
156     1994_WYOMING    WYOMING  1994  100899.0       674921.0   
208     1995_WYOMING    WYOMING  1995  100314.0       634237.0   
259     1996_WYOMING    WYOMING  1996   99859.0       664057.0   
311     1997_WYOMING    WYOMING  1997   98777.0       660079.0   
362     1998_WYOMING    WYOMING  1998   96504.0       703280.0   
415     1999_WYOMING    WYOMING  1999   94420.0       780875.0   
467     2000_WYOMING    WYOMING  2000   91883.0       787323.0   
36      2001_WYOMING    WYOMING  2001   89711.0       804297.0   
571     2002_WYOMING    WYOMING  2002   87897.0       908719.0   
623     2003_WYOMING    WYOMING  2003   85966.0       962240.0   
675     2004_WYOMING    WYOMING  2004   86925.0       974888.0   
726     2005_WYOMING    WYOMING  2005   84146.0      1132160.0   
779     2006_WYOMING    WYOMING  2006   86155.0      1150345.0   
831     2007_WYOMING    WYOMING  2007   85034.0      1477891.0   
886     2008_WYOMING    WYOMING  2008   85991.0      1602514.0   
939     2009_WYOMING    WYOMING  2009   86971.0      1675761.0   
992     2010_WYOMING    WYOMING  2010   87379.0      1718605.0   
1043    2011_WYOMING    WYOMING  2011   88165.0      1650621.0   
1095    2012_WYOMING    WYOMING  2012   89994.0      1664983.0   
1147    2013_WYOMING    WYOMING  2013   91533.0      1695967.0   
1198    2014_WYOMING    WYOMING  2014   92732.0      1772633.0   
1249    2015_WYOMING    WYOMING  2015   93867.0      1962874.0   
881     2016_WYOMING    WYOMING  2016   94511.0  

In [81]:
for state in edu_df['STATE'].unique(): 
    edu_df.loc[edu_df['STATE'] == state] = edu_1.loc[edu_1['STATE'] == state].interpolate(method = 'linear', limit_direction = 'both')
edu_df.dropna(inplace = True)
edu_df['WEIGHTED_SCORES'] = (edu_df['GRADES_4_G']*edu_df['AVG_MATH_4_SCORE'] + edu_df['GRADES_8_G']*edu_df['AVG_MATH_8_SCORE'] + edu_df['GRADES_4_G']*edu_df['AVG_READING_4_SCORE'] + edu_df['GRADES_8_G']*edu_df['AVG_READING_8_SCORE'])/(2*edu_df['GRADES_4_G'] + 2*edu_df['GRADES_8_G'])
edu_df

PRIMARY_KEY      STATE  YEAR    ENROLL  TOTAL_REVENUE  \
0       1992_ALABAMA    ALABAMA  1992  727716.0      2678885.0   
52      1993_ALABAMA    ALABAMA  1993  727716.0      2827391.0   
104     1994_ALABAMA    ALABAMA  1994  730004.0      2970223.0   
157     1995_ALABAMA    ALABAMA  1995  727480.0      3367437.0   
209     1996_ALABAMA    ALABAMA  1996  735912.0      3365113.0   
260     1997_ALABAMA    ALABAMA  1997  737386.0      3981788.0   
312     1998_ALABAMA    ALABAMA  1998  739321.0      4140537.0   
363     1999_ALABAMA    ALABAMA  1999  737639.0      4471546.0   
416     2000_ALABAMA    ALABAMA  2000  730184.0      4885917.0   
468     2001_ALABAMA    ALABAMA  2001  728532.0      4832946.0   
520     2002_ALABAMA    ALABAMA  2002  726367.0      5128559.0   
572     2003_ALABAMA    ALABAMA  2003  727900.0      5196054.0   
624     2004_ALABAMA    ALABAMA  2004  730418.0      5356113.0   
676     2005_ALABAMA    ALABAMA  2005  729342.0      5889966.0   
727     2006_ALABAMA    ALABAMA  2006  743265.0      6364028.0   
780     2007_ALABAMA    ALABAMA  2007  743273.0      7069040.0   
832     2008_ALABAMA    ALABAMA  2008  742919.0      7726213.0   
887     2009_ALABAMA    ALABAMA  2009  745668.0      7186390.0   
940     2010_ALABAMA    ALABAMA  2010  748889.0      7281058.0   
993     2011_ALABAMA    ALABAMA  2011  746933.0      7376725.0   
1044    2012_ALABAMA    ALABAMA  2012  744621.0      7136949.0   
1096    2013_ALABAMA    ALABAMA  2013  744548.0      7197439.0   
1148    2014_ALABAMA    ALABAMA  2014  740081.0      7357267.0   
1199    2015_ALABAMA    ALABAMA  2015  734974.0      7360222.0   
1250    2016_ALABAMA    ALABAMA  2016  734652.0      7498567.0   
1447    2017_ALABAMA    ALABAMA  2017  734652.0      7498567.0   
1        1992_ALASKA     ALASKA  1992  121156.0      1049591.0   
53       1993_ALASKA     ALASKA  1993  121156.0      1191398.0   
105      1994_ALASKA     ALASKA  1994  123868.0      1052282.0   
158      1995_ALASKA     ALASKA  1995  125421.0      1117068.0   
...              ...        ...   ...       ...            ...   
1197  2014_WISCONSIN  WISCONSIN  2014  865119.0     11330253.0   
1248  2015_WISCONSIN  WISCONSIN  2015  861813.0     11637376.0   
808   2016_WISCONSIN  WISCONSIN  2016  857736.0     11697466.0   
1490  2017_WISCONSIN  WISCONSIN  2017  857736.0     11697466.0   
51      1992_WYOMING    WYOMING  1992  100313.0       629748.0   
103     1993_WYOMING    WYOMING  1993  100313.0       615130.0   
156     1994_WYOMING    WYOMING  1994  100899.0       674921.0   
208     1995_WYOMING    WYOMING  1995  100314.0       634237.0   
259     1996_WYOMING    WYOMING  1996   99859.0       664057.0   
311     1997_WYOMING    WYOMING  1997   98777.0       660079.0   
362     1998_WYOMING    WYOMING  1998   96504.0       703280.0   
415     1999_WYOMING    WYOMING  1999   94420.0       780875.0   
467     2000_WYOMING    WYOMING  2000   91883.0       787323.0   
36      2001_WYOMING    WYOMING  2001   89711.0       804297.0   
571     2002_WYOMING    WYOMING  2002   87897.0       908719.0   
623     2003_WYOMING    WYOMING  2003   85966.0       962240.0   
675     2004_WYOMING    WYOMING  2004   86925.0       974888.0   
726     2005_WYOMING    WYOMING  2005   84146.0      1132160.0   
779     2006_WYOMING    WYOMING  2006   86155.0      1150345.0   
831     2007_WYOMING    WYOMING  2007   85034.0      1477891.0   
886     2008_WYOMING    WYOMING  2008   85991.0      1602514.0   
939     2009_WYOMING    WYOMING  2009   86971.0      1675761.0   
992     2010_WYOMING    WYOMING  2010   87379.0      1718605.0   
1043    2011_WYOMING    WYOMING  2011   88165.0      1650621.0   
1095    2012_WYOMING    WYOMING  2012   89994.0      1664983.0   
1147    2013_WYOMING    WYOMING  2013   91533.0      1695967.0   
1198    2014_WYOMING    WYOMING  2014   92732.0      1772633.0   
1249    2015_WYOMING    WYOMING  2015   93867.0      1962874.0   
881     2016_WYOMING    WYOMING  2016   94511.0  

In [82]:
edu_corr = edu_df[['WEIGHTED_SCORES', "INSTRUCTION_EXPENDITURE", "SUPPORT_SERVICES_EXPENDITURE", "OTHER_EXPENDITURE", "CAPITAL_OUTLAY_EXPENDITURE"]].corr()
edu_corr

WEIGHTED_SCORES  INSTRUCTION_EXPENDITURE  \
WEIGHTED_SCORES                      1.000000                 0.133105   
INSTRUCTION_EXPENDITURE              0.133105                 1.000000   
SUPPORT_SERVICES_EXPENDITURE         0.134274                 0.976228   
OTHER_EXPENDITURE                    0.062597                 0.908494   
CAPITAL_OUTLAY_EXPENDITURE           0.060536                 0.893354   

                              SUPPORT_SERVICES_EXPENDITURE  OTHER_EXPENDITURE  \
WEIGHTED_SCORES                                   0.134274           0.062597   
INSTRUCTION_EXPENDITURE                           0.976228           0.908494   
SUPPORT_SERVICES_EXPENDITURE                      1.000000           0.953215   
OTHER_EXPENDITURE                                 0.953215           1.000000   
CAPITAL_OUTLAY_EXPENDITURE                        0.915092           0.920356   

                              CAPITAL_OUTLAY_EXPENDITURE  
WEIGHTED_SCORES                                 0.060536  
INSTRUCTION_EXPENDITURE                         0.893354  
SUPPORT_SERVICES_EXPENDITURE                    0.915092  
OTHER_EXPENDITURE                               0.920356  
CAPITAL_OUTLAY_EXPENDITURE                      1.000000

In [85]:
sklearn_pca = PCA(n_components = 4)
X = StandardScaler().fit_transform(edu_df[['WEIGHTED_SCORES', "INSTRUCTION_EXPENDITURE", "SUPPORT_SERVICES_EXPENDITURE", "OTHER_EXPENDITURE", "CAPITAL_OUTLAY_EXPENDITURE"]])
Y_sklearn = sklearn_pca.fit_transform(X)
print(
    'The percentage of total variance in the dataset explained by each',
    'component from Sklearn PCA.\n',
    sklearn_pca.explained_variance_ratio_
)

[[-1.15050966  2.00972163 -0.12702979 -0.09801784]
 [-1.11341194  1.85724718 -0.11241836 -0.0869885 ]
 [-1.01752706  1.78226081 -0.08132009 -0.17352217]
 ...
 [-1.09710063 -0.97481877  0.22330821  0.15682342]
 [-1.06244339 -1.14603875  0.25654383  0.16866958]
 [-1.05022797 -1.31991957  0.2694805   0.16463792]]
The percentage of total variance in the dataset explained by each component from Sklearn PCA.
 [0.75950725 0.19839077 0.02391675 0.01547248]


In [98]:
edu_comp = pd.DataFrame(edu_df['WEIGHTED_SCORES'])
Y_sklearn = pd.DataFrame(Y_sklearn)
edu_comp['Component 1'] = Y_sklearn[0]
edu_comp['Component 2'] = Y_sklearn[1]
edu_comp['Component 3'] = Y_sklearn[2]
edu_comp['Component 4'] = Y_sklearn[3]
edu_comp.corr()

WEIGHTED_SCORES  Component 1  Component 2  Component 3  \
WEIGHTED_SCORES         1.000000     0.008880    -0.254855    -0.009944   
Component 1             0.008880     1.000000    -0.005721     0.004165   
Component 2            -0.254855    -0.005721     1.000000     0.000926   
Component 3            -0.009944     0.004165     0.000926     1.000000   
Component 4             0.080175     0.005151     0.000577    -0.006161   

                 Component 4  
WEIGHTED_SCORES     0.080175  
Component 1         0.005151  
Component 2         0.000577  
Component 3        -0.006161  
Component 4         1.000000