In [150]:
import pandas as pd
import numpy as np

amazon_df = pd.read_fwf('amazon_cells_labelled.txt')
amazon_df

Raw_Text
0    So there is no way for me to plug it in here i...
1                       Good case, Excellent value.\t1
2                            Great for the jawbone.\t1
3    Tied to charger for conversations lasting more...
4                                 The mic is great.\t1
5    I have to jiggle the plug to get it to line up...
6    If you have several dozen or several hundred c...
7       If you are Razr owner...you must have this!\t1
8               Needless to say, I wasted my money.\t0
9                  What a waste of money and time!.\t0
10                  And the sound quality is great.\t1
11   He was very impressed when going from the orig...
12   If the two were seperated by a mere 5+ ft I st...
13                         Very good quality though\t1
14   The design is very odd, as the ear "clip" is n...
15   Highly recommend for any one who has a blue to...
16              I advise EVERYONE DO NOT BE FOOLED!\t0
17                                 So Far So Good!.\t1
18                                    Works great!.\t1
19   It clicks into place in a way that makes you w...
20   I went on Motorola's website and followed all ...
21   I bought this to use with my Kindle Fire and a...
22         The commercials are the most misleading.\t0
23   I have yet to run this new battery below two b...
24   I bought it for my mother and she had a proble...
25             Great Pocket PC / phone combination.\t1
26   I've owned this phone for 7 months now and can...
27   I didn't think that the instructions provided ...
28   People couldnt hear me talk and I had to pull ...
29                             Doesn't hold charge.\t0
..                                                 ...
970  I plugged it in only to find out not a darn th...
971                              Excellent product.\t1
972                     Earbud piece breaks easily.\t0
973                                  Lousy product.\t0
974  This phone tries very hard to do everything bu...
975  It is the best charger I have seen on the mark...
976                               SWEETEST PHONE!!!\t1
977          :-)Oh, the charger seems to work fine.\t1
978  It fits so securely that the ear hook does not...
979                              Not enough volume.\t0
980             Echo Problem....Very unsatisfactory\t0
981  you could only take 2 videos at a time and the...
982                         don't waste your money.\t0
983  I am going to have to be the first to negative...
984  Adapter does not provide enough charging curre...
985  There was so much hype over this phone that I ...
986  You also cannot take pictures with it in the c...
987                         Phone falls out easily.\t0
988  It didn't work, people can not hear me when I ...
989  The text messaging feature is really tricky to...
990  I'm really disappointed all I have now is a ch...
991                             Painful on the ear.\t0
992                Lasted one day and then blew up.\t0
993                                   disappointed.\t0
994                           Kind of flops around.\t0
995  The screen does get smudged easily because it ...
996  What a piece of junk.. I lose more calls on th...
997                    Item Does Not Match Picture.\t0
998  The only thing that disappoint me is the infra...
999  You can not answer calls with the unit, never ...

[1000 rows x 1 columns]

In [151]:
split_text = amazon_df['Raw_Text'].str.split("\t")
reviews = []
sentiments = []
for i in range(len(split_text)):
    reviews.append(split_text[i][0])
    sentiments.append(int(split_text[i][1]))
amazon_df['Review'] = reviews
amazon_df['Sentiment'] = sentiments
amazon_df

Raw_Text  \
0    So there is no way for me to plug it in here i...   
1                       Good case, Excellent value.\t1   
2                            Great for the jawbone.\t1   
3    Tied to charger for conversations lasting more...   
4                                 The mic is great.\t1   
5    I have to jiggle the plug to get it to line up...   
6    If you have several dozen or several hundred c...   
7       If you are Razr owner...you must have this!\t1   
8               Needless to say, I wasted my money.\t0   
9                  What a waste of money and time!.\t0   
10                  And the sound quality is great.\t1   
11   He was very impressed when going from the orig...   
12   If the two were seperated by a mere 5+ ft I st...   
13                         Very good quality though\t1   
14   The design is very odd, as the ear "clip" is n...   
15   Highly recommend for any one who has a blue to...   
16              I advise EVERYONE DO NOT BE FOOLED!\t0   
17                                 So Far So Good!.\t1   
18                                    Works great!.\t1   
19   It clicks into place in a way that makes you w...   
20   I went on Motorola's website and followed all ...   
21   I bought this to use with my Kindle Fire and a...   
22         The commercials are the most misleading.\t0   
23   I have yet to run this new battery below two b...   
24   I bought it for my mother and she had a proble...   
25             Great Pocket PC / phone combination.\t1   
26   I've owned this phone for 7 months now and can...   
27   I didn't think that the instructions provided ...   
28   People couldnt hear me talk and I had to pull ...   
29                             Doesn't hold charge.\t0   
..                                                 ...   
970  I plugged it in only to find out not a darn th...   
971                              Excellent product.\t1   
972                     Earbud piece breaks easily.\t0   
973                                  Lousy product.\t0   
974  This phone tries very hard to do everything bu...   
975  It is the best charger I have seen on the mark...   
976                               SWEETEST PHONE!!!\t1   
977          :-)Oh, the charger seems to work fine.\t1   
978  It fits so securely that the ear hook does not...   
979                              Not enough volume.\t0   
980             Echo Problem....Very unsatisfactory\t0   
981  you could only take 2 videos at a time and the...   
982                         don't waste your money.\t0   
983  I am going to have to be the first to negative...   
984  Adapter does not provide enough charging curre...   
985  There was so much hype over this phone that I ...   
986  You also cannot take pictures with it in the c...   
987                         Phone falls out easily.\t0   
988  It didn't work, people can not hear me when I ...   
989  The text messaging feature is really tricky to...   
990  I'm really disappointed all I have now is a ch...   
991                             Painful on the ear.\t0   
992                Lasted one day and then blew up.\t0   
993                                   disappointed.\t0   
994                           Kind of flops around.\t0   
995  The screen does get smudged easily because it ...   
996  What a piece of junk.. I lose more calls on th...   
997                    Item Does Not Match Picture.\t0   
998  The only thing that disappoint me is the infra...   
999  You can not answer calls with the unit, never ...   

                                                Review  Sentiment  
0    So there is no way for me to plug it in here i...          0  
1                          Good case, Excellent value.          1  
2                               Great for the jawbone.          1  
3    Tied to charger for conversations lasting more...          0  
4                                    The mic is great.          1  
5    I have to jiggle the plug to get it 

In [153]:
good_reviews = amazon_df.loc[amazon_df['Sentiment'] == 1]['Review']
word_dict = {}
for review in good_reviews:
    words = review.split(" ")
    for word in set(words):
        if word in word_dict.keys():
            word_dict[word] = word_dict.get(word) + 1
        else:
            word_dict.update({word: 1})
sorted_word_dict = [(k, word_dict[k]) for k in sorted(word_dict, key=word_dict.get, reverse=True)]
print(sorted_word_dict)

[('and', 163), ('the', 147), ('I', 132), ('is', 119), ('a', 88), ('to', 77), ('this', 68), ('it', 60), ('with', 59), ('very', 57), ('for', 55), ('my', 53), ('phone', 49), ('The', 45), ('of', 45), ('on', 41), ('good', 38), ('It', 36), ('have', 34), ('in', 33), ('was', 32), ('This', 32), ('great', 31), ('Great', 30), ('works', 28), ('that', 27), ('has', 23), ('quality', 21), ('headset', 21), ('are', 20), ('one', 20), ('so', 20), ('recommend', 18), ('like', 18), ('than', 18), ('but', 18), ('sound', 17), ('had', 17), ('you', 16), ('from', 16), ('phone.', 16), ("I've", 16), ('as', 16), ('love', 16), ('great.', 15), ('best', 15), ('well', 15), ('would', 15), ('any', 14), ('Works', 14), ('all', 14), ('Good', 13), ('product', 13), ('it.', 13), ('-', 13), ('your', 13), ('Excellent', 12), ('battery', 12), ('use', 12), ('well.', 12), ('not', 12), ('been', 12), ('happy', 12), ('really', 12), ('am', 12), ('can', 11), ('up', 11), ('even', 11), ('product.', 11), ('Very', 10), ('nice', 10), ('price', 

In [154]:
bad_reviews = amazon_df.loc[amazon_df['Sentiment'] == 0]['Review']
word_dict = {}
for review in bad_reviews:
    words = review.split(" ")
    for word in set(words):
        if word in word_dict.keys():
            word_dict[word] = word_dict.get(word) + 1
        else:
            word_dict.update({word: 1})
sorted_word_dict = [(k, word_dict[k]) for k in sorted(word_dict, key=word_dict.get, reverse=True)]
print(sorted_word_dict)

[('the', 165), ('I', 131), ('and', 104), ('a', 94), ('it', 92), ('to', 91), ('is', 86), ('not', 75), ('this', 70), ('of', 65), ('my', 58), ('phone', 55), ('The', 52), ('for', 51), ('in', 49), ('with', 43), ('was', 43), ('on', 42), ('that', 39), ('have', 35), ('you', 31), ('had', 26), ('It', 24), ('but', 23), ('This', 21), ('very', 19), ('your', 18), ('it.', 18), ('as', 17), ('from', 16), ('are', 16), ('only', 16), ('at', 15), ('would', 15), ('out', 15), ('battery', 15), ('work', 15), ('or', 14), ('Not', 14), ('use', 14), ('be', 14), ('me', 13), ('get', 13), ('all', 13), ('after', 13), ('good', 13), ('when', 13), ('if', 13), ('then', 12), ('sound', 12), ('could', 12), ('phone.', 12), ("don't", 12), ('If', 11), ('one', 11), ('waste', 11), ('first', 11), ('like', 11), ('product', 11), ('about', 11), ('too', 11), ("I'm", 11), ('so', 11), ('quality', 11), ("Don't", 11), ('will', 11), ('no', 10), ('up', 10), ('hear', 10), ('time', 10), ('buy', 10), ('enough', 10), ('-', 10), ('2', 10), ('thi

In [265]:
keyword1 = ['good', 'great', 'excellent', 'not good', 'best', 'disappoint', 'fine']
keyword2 = ['bad', 'terrible', 'waste', 'disappoint', 'unsatisfactory', 'first', 'perfect']

In [247]:
keywords = ['good', 'great', 'excellent', 'bad', 'terrible', 'waste', 'not good', 'best', 'disappointed', 'disappoint', 'fine', 'unsatisfactory', 'quality', 'recommend', 'happy', 'first', 'the']

for key in keyword1:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    amazon_df[str(key)] = amazon_df.Review.str.contains(str(key),case=False)
for key in keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    amazon_df[str(key)] = amazon_df.Review.str.contains(str(key),case=False)

amazon_df['allcaps'] = amazon_df.Review.str.isupper()
amazon_df['Positive Review'] = (amazon_df['Sentiment'] == 1)
amazon_df.loc[amazon_df['not good'] == True]

Raw_Text  \
455      Not good when wearing a hat or sunglasses.\t0   
637  However, BT headsets are currently not good fo...   
741  Couldn't use the unit with sunglasses, not goo...   
848                  Not good enough for the price.\t0   

                                                Review  Sentiment  good  \
455         Not good when wearing a hat or sunglasses.          0  True   
637  However, BT headsets are currently not good fo...          0  True   
741  Couldn't use the unit with sunglasses, not goo...          0  True   
848                     Not good enough for the price.          0  True   

     great  excellent    bad  terrible  waste  not good  ...  disappoint  \
455  False      False  False     False  False      True  ...       False   
637  False      False  False     False  False      True  ...       False   
741  False      False  False     False  False      True  ...       False   
848  False      False  False     False  False      True  ...       False   

      fine  unsatisfactory  quality  recommend  happy  first  allcaps  \
455  False           False    False      False  False  False    False   
637  False           False    False      False  False   True    False   
741  False           False    False      False  False  False    False   
848  False           False    False      False  False  False    False   

     Positive Review    the  
455            False  False  
637            False   True  
741            False   True  
848            False   True  

[4 rows x 22 columns]

In [248]:
#amazon_df[['good', 'great', 'excellent']]
amazon_df.columns
amazon_df[['good', 'great', 'excellent', 'bad',
       'terrible', 'waste', 'allcaps',
       'Positive Review', 'not good', 'best', 'disappointed', 'disappoint', 'fine', 'unsatisfactory', 'quality', 
        'recommend', 'happy', 'first']].corr()

good     great  excellent       bad  terrible     waste  \
good             1.000000 -0.042779  -0.000586 -0.033930 -0.028618 -0.036310   
great           -0.042779  1.000000  -0.054908 -0.039277 -0.033128 -0.042031   
excellent       -0.000586 -0.054908   1.000000 -0.019850 -0.016742 -0.021242   
bad             -0.033930 -0.039277  -0.019850  1.000000 -0.011976 -0.015195   
terrible        -0.028618 -0.033128  -0.016742 -0.011976  1.000000  0.067283   
waste           -0.036310 -0.042031  -0.021242 -0.015195  0.067283  1.000000   
allcaps         -0.035139 -0.040676   0.030201 -0.014705 -0.012403 -0.015736   
Positive Review  0.186035  0.289256   0.154242 -0.119159 -0.100504 -0.127515   
not good         0.222557 -0.020889  -0.010557 -0.007551 -0.006369 -0.008081   
best            -0.016824 -0.026507  -0.024984 -0.017872 -0.015074 -0.019125   
disappointed    -0.028618 -0.033128  -0.016742 -0.011976 -0.010101 -0.012816   
disappoint       0.011253 -0.048276  -0.024397 -0.017452 -0.014720 -0.018676   
fine             0.034355 -0.008136  -0.019118 -0.013675 -0.011534 -0.014634   
unsatisfactory  -0.009009 -0.010429  -0.005270 -0.003770 -0.003180 -0.004034   
quality          0.111242 -0.043658   0.076511  0.012381  0.023745 -0.028945   
recommend       -0.047434 -0.013405   0.010316  0.032663 -0.016742 -0.021242   
happy            0.021293 -0.043347  -0.021907 -0.015670 -0.013217 -0.016769   
first            0.043799 -0.045872  -0.023183  0.045760 -0.013987 -0.017746   

                  allcaps  Positive Review  not good      best  disappointed  \
good            -0.035139         0.186035  0.222557 -0.016824     -0.028618   
great           -0.040676         0.289256 -0.020889 -0.026507     -0.033128   
excellent        0.030201         0.154242 -0.010557 -0.024984     -0.016742   
bad             -0.014705        -0.119159 -0.007551 -0.017872     -0.011976   
terrible        -0.012403        -0.100504 -0.006369 -0.015074     -0.010101   
waste           -0.015736        -0.127515 -0.008081 -0.019125     -0.012816   
allcaps          1.000000        -0.041135 -0.007820 -0.018508      0.070281   
Positive Review -0.041135         1.000000 -0.063372  0.122713     -0.100504   
not good        -0.007820        -0.063372  1.000000 -0.009505     -0.006369   
best            -0.018508         0.122713 -0.009505  1.000000     -0.015074   
disappointed     0.070281        -0.100504 -0.006369 -0.015074      1.000000   
disappoint       0.039303        -0.146460 -0.009282 -0.021966      0.686221   
fine            -0.014163         0.097110 -0.007273 -0.017213     -0.011534   
unsatisfactory  -0.003904        -0.031639 -0.002005 -0.004745     -0.003180   
quality         -0.028011         0.060222 -0.014385  0.029118     -0.022813   
recommend       -0.020557         0.092545 -0.010557 -0.024984     -0.016742   
happy           -0.016228         0.069621 -0.008334 -0.019724     -0.013217   
first           -0.017174        -0.109870  0.107226 -0.020873     -0.013987   

                 disappoint      fine  unsatisfactory   quality  recommend  \
good               0.011253  0.034355       -0.009009  0.111242  -0.047434   
great             -0.048276 -0.008136       -0.010429 -0.043658  -0.013405   
excellent         -0.024397 -0.019118       -0.005270  0.076511   0.010316   
bad               -0.017452 -0.013675       -0.003770  0.012381   0.032663   
terrible          -0.014720 -0.011534       -0.003180  0.023745  -0.016742   
waste             -0.018676 -0.014634       -0.004034 -0.028945  -0.021242   
allcaps            0.039303 -0.014163       -0.003904 -0.028011  -0.020557   
Positive Review   -0.146460  0.097110       -0.031639  0.060222   0.092545   
not good          -0.009282 -0.007273       -0.002005 -0.014385  -0.010557   
best              -0.021966 -0.017213       -0.004745  0.029118  -0.024984   
disappointed       0.686221 -0.011534       -0.003180 -0.022813  -0.016742   
disappoint         1.000000 -0.016809      

In [249]:
data = amazon_df[['good', 'great', 'excellent', 'bad',
       'terrible', 'waste', 'allcaps','not good', 'best', 'disappointed', 'disappoint', 'fine', 'unsatisfactory', 'first']]
target = amazon_df['Positive Review']
# Our data is binary / boolean, so we're importing the Bernoulli classifier.
from sklearn.naive_bayes import BernoulliNB

# Instantiate our model and store it in a new variable.
bnb = BernoulliNB()

# Fit our model to the data.
bnb.fit(data, target)

# Classify, storing the result in a new variable.
y_pred = bnb.predict(data)

# Display our results.
print("Number of mislabeled points out of a total {} points : {}".format(
    data.shape[0],
    (target != y_pred).sum()
))

Number of mislabeled points out of a total 1000 points : 316


In [250]:
imdb_file = open('imdb_labelled.txt', 'r')
imdb_text = imdb_file.read()
imdb_text = imdb_text.split("\n")
reviews = []
sentiments = []
for text in imdb_text:
    splt = text.split('\t')
    reviews.append(splt[0])
    sentiments.append(splt[1])
imdf = pd.DataFrame()
imdf['Review'] = reviews
imdf['Sentiment'] = sentiments
imdf.head()

Review Sentiment
0  A very, very, very slow-moving, aimless movie ...         0
1  Not sure who was more lost - the flat characte...         0
2  Attempting artiness with black & white and cle...         0
3       Very little music or anything to speak of.           0
4  The best scene in the movie was when Gerardo i...         1

In [266]:
keywords = ['good', 'great', 'excellent', 'bad', 'terrible', 'waste', 'not good', 'best', 'disappointed', 'disappoint', 'fine', 'unsatisfactory', 'quality', 'recommend', 'happy', 'first', 'the']

for key in keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    imdf[str(key)] = imdf.Review.str.contains(str(key),case=False)

for key in keyword2:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    imdf[str(key)] = imdf.Review.str.contains(str(key),case=False)
    
imdf['allcaps'] = imdf.Review.str.isupper()
imdf['Positive Review'] = (imdf['Sentiment'] == '1')
imdf.head()

Review Sentiment   good  great  \
0  A very, very, very slow-moving, aimless movie ...         0  False  False   
1  Not sure who was more lost - the flat characte...         0  False  False   
2  Attempting artiness with black & white and cle...         0  False  False   
3       Very little music or anything to speak of.           0  False  False   
4  The best scene in the movie was when Gerardo i...         1  False  False   

   excellent    bad  terrible  waste  not good   best  ...  recommend  happy  \
0      False  False     False  False     False  False  ...      False  False   
1      False  False     False  False     False  False  ...      False  False   
2      False  False     False  False     False  False  ...      False  False   
3      False  False     False  False     False  False  ...      False  False   
4      False  False     False  False     False   True  ...      False  False   

   first    the   love   cool    fun  allcaps  Positive Review  perfect  
0  False  False  False  False  False    False            False    False  
1  False   True  False  False  False    False            False    False  
2  False   True  False  False  False    False            False    False  
3  False  False  False  False  False    False            False    False  
4  False   True  False  False  False    False             True    False  

[5 rows x 25 columns]

In [267]:
data2 = imdf[['good', 'great', 'excellent',
       'terrible', 'waste', 'allcaps','not good', 'best', 'disappointed', 'disappoint', 'fine', 'unsatisfactory', 'first']]
target2 = imdf['Positive Review']
# Our data is binary / boolean, so we're importing the Bernoulli classifier.

# Instantiate our model and store it in a new variable.
bnb2 = BernoulliNB()

# Fit our model to the data.
bnb2.fit(data2, target2)

# Classify, storing the result in a new variable.
y_pred2 = bnb2.predict(data2)

# Display our results.
print("Number of mislabeled points out of a total {} points : {}".format(
    data2.shape[0],
    (target2 != y_pred2).sum()
))

Number of mislabeled points out of a total 1000 points : 418


In [268]:
from sklearn.model_selection import train_test_split
# Use train_test_split to create the necessary training and test groups
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=20)
print('With 20% Holdout: ' + str(bnb.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(bnb.fit(data, target).score(data, target)))

With 20% Holdout: 0.66
Testing on Sample: 0.684


In [269]:
# Use train_test_split to create the necessary training and test groups
X_train2, X_test2, y_train2, y_test2 = train_test_split(data2, target2, test_size=0.2, random_state=20)
print('With 20% Holdout: ' + str(bnb.fit(X_train2, y_train2).score(X_test2, y_test2)))
print('Testing on Sample: ' + str(bnb.fit(data2, target2).score(data2, target2)))

With 20% Holdout: 0.61
Testing on Sample: 0.582


In [270]:
from sklearn.model_selection import cross_val_score
cross_val_score(bnb, data, target, cv=10)

array([0.7 , 0.71, 0.74, 0.69, 0.68, 0.68, 0.65, 0.64, 0.71, 0.62])

In [271]:
cross_val_score(bnb, data2, target2, cv=10)

array([0.59, 0.54, 0.57, 0.61, 0.64, 0.59, 0.59, 0.58, 0.59, 0.51])

In [272]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target, y_pred)

array([[483,  17],
       [299, 201]])

In [273]:
confusion_matrix(target2, y_pred2)

array([[472,  28],
       [390, 110]])

In [275]:
key2 = ['bad', 'terrible', 'waste', 'disappoint', 'unsatisfactory', 'first']
data = amazon_df[keyword1]
target = amazon_df['Positive Review']
bnb = BernoulliNB()
bnb.fit(data, target)
y_pred = bnb.predict(data)
print((target == y_pred).sum()/len(target))
print(confusion_matrix(target, y_pred))
data2 = imdf[key2]
target2 = imdf['Positive Review']
bnb2 = BernoulliNB()
bnb2.fit(data2, target2)
y_pred2 = bnb2.predict(data2)
print((target2 == y_pred2).sum()/len(target2))
print(confusion_matrix(target2, y_pred2))

0.684
[[483  17]
 [299 201]]
0.592
[[104 396]
 [ 12 488]]


In [276]:
cross_val_score(bnb, data, target, cv=10)

array([0.7 , 0.71, 0.74, 0.69, 0.68, 0.68, 0.65, 0.64, 0.71, 0.62])

In [277]:
cross_val_score(bnb2, data2, target2, cv=10)

array([0.56, 0.56, 0.57, 0.59, 0.61, 0.58, 0.64, 0.6 , 0.55, 0.61])